name: CI

on:
  # Triggers the workflow on pull request events but only for the "master" branch
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install black and flake8
        run: python3 -m pip install black flake8

      - name: Run flake8
        run: flake8 --select=C,E,F,W,D,A,I,B --ignore=B950,E501,W503 casq test

      - name: Run black
        run: black --check --diff casq test
